version: "3"
services:
  app:
    build: .
    tty: true
    ports:
      - 8080:8080
    volumes:
      - .:/app
    command: ["sh", "gradlew", "bootRun"]
    depends_on:
      - db
  db:
    image: mysql:8.0.30
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app_db
      MYSQL_PASSWORD: root
      MYSQL_USER: user
      MYSQL_USER_PASSWORD: user
      TZ: 'Asia/Tokyo'
    ports:
      - 3306:3306
    tty: true
    command: mysqld --character-set-server=utf8mb4 --explicit_defaults_for_timestamp=true --default-authentication-plugin=mysql_native_password
